# Generated by Django 4.0.4 on 2022-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('a_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('q_date', models.DateTimeField(verbose_name='data published')),
                ('q_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('q_like_count', models.PositiveIntegerField(default=0)),
                ('q_clicks', models.PositiveIntegerField(default=0, verbose_name='QnA_조회수')),
            ],
        ),
    ]
