# Generated by Django 4.0.4 on 2022-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_comment',
            name='rc_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
